### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by edgrosvenor** [EXACTsports/fedex#1]
### Background

EXACT Sports runs events across the country. For each event, we create handouts for the attendees. Currently, we generate PDFs offline and upload them to FedEx Office for printing at a nearby location. The goal of this package is to remove, as much as possible, the human interaction required to place these print orders. In a separate project, we are working on a system that will automatically generate the PDFs we want printed and calculate how many of each we need. This package will just handle the interaction with FedEx Office. At a minimum, it will include the following:

- [ ] A UI to select the desired FedEx Office location from a list of locations near the venue address. This list must include the nearest 24-hour location to the venue address even if that location is outside the default search radius and / or is not one of the closest X locations, where X is the number of results requested.
- [ ] Upload the PDFs associated with an event to FedEx Office via their API
- [ ] Add quantity, paper size, and other required parameters to each PDF

There are still some questions we need to answer with regard to how the actual order workflow will happen. In most cases, I believe it will be desirable to have a user of our app (the app that will pull in this package) approve the order and send it with the click of a button. I believe it will usually make sense to have the order billed to our FedEx account, but we'll definitely want credit card billing enabled in case the account billing fails (and obviously for any others who eventually use this package).

**Comment by barrytarter** [comment]
@jlnmay here is a possible UI to help show the above features & API request required for submitting print orders to Fedex: https://docs.google.com/spreadsheets/d/1W5OjWgMLbjTrc5kPsbrZ2ARBbmSPLYddRUYDyqpmj_g/edit#gid=1680315437

As you can see below, key push elements are the (a) location selection (search by address?), (b) upload function for PDFs, (c) putting the name on order in and selecting credit card, (d) setting print order details like quantity and paper types.  Also, we'll need to store response information from the API: (e) submission start timestamp, (f) error messages encountered if failed, (g) submission end timestamp (which will trigger an email that @edgrosvenor would send), (h) amount paid, (i) fedex email, (j) pickup date/time for order.

![image](https://user-images.githubusercontent.com/1317246/121427398-48b46480-c93a-11eb-8e61-f4e12038f54f.png)
