### ISSUE TITLE
Replace all use of Redis with Cache facade

### ISSUE THREAD

**Issue by edgrosvenor** [EXACTsports/fedex#4]
While Redis makes a good option for caching, it's not the only option. We shouldn't lock anyone, including ourselves, into using it. Replacing all instances of Redis with the Laravel Cache facade will let users choose the cache driver that works best for them.

**Comment by jlnmay** [comment]
Got it. @edgrosvenor @barrytarter, taking care of this

**Comment by jlnmay** [comment]
Replaced all Redis instances with the Laravel Cache facade
@edgrosvenor @barrytarter done!
Ohh I think has been addressed by you @edgrosvenor, I just read your email.
