### ISSUE TITLE
Location listings don't appear to be correct

### ISSUE THREAD

**Issue by edgrosvenor** [EXACTsports/fedex#6]
Using my home address: `17976 W Big Oaks Rd. Grayslake, IL 60030` I get the following listings:

![image](https://user-images.githubusercontent.com/1053395/146441623-d04cba08-b37e-425b-8f48-ad641a0fa66f.png)

However, if I search for FedEx office in Google from my current location, I get a bigger list and several of the listings are definitely closer than the ones on the list above.

<img width="418" alt="Screen Shot 2021-12-16 at 14 06 50" src="https://user-images.githubusercontent.com/1053395/146441787-72c2871d-0080-4c44-a8b8-238911256e63.png">

As you can see, in the image at the top the Vernon Hills location is at the top, implying it's the closest. The image from Google has it pretty far down the list and I can verify that at least most of those above it are, in fact, closer.

**Comment by edgrosvenor** [comment]
@jlnmay One thing that would be really helpful would be to replace the constants that appear under the location name with an actual street address. I can't verify looking at the listings at the top that these are, in fact, print and ship locations. If they're not, that might be why I'm getting the 503 Not Implemented error.

**Comment by barrytarter** [comment]
@jlnmay thanks for the update.  Feel free to test out diffrent addresses using both google maps (to see what comes up for nearby distances) as well as the fedex.com search function. I'd recommend using USA addresses to test it out (e.g. in Chicago, San Diego, and other US cities).

**Comment by jlnmay** [comment]
@edgrosvenor @barrytarter 
I have figured out this after testing, reading documentation again and comparing with FedEx platform.
Well first of all, I searched in their platform and got this result 
![Screen Shot 2021-12-31 at 14 54 47](https://user-images.githubusercontent.com/6946122/147838760-cbe9c3c9-d125-4b28-8fa3-efccddd743b2.png)
I created a test in fedex library, also tested the endpoint with postman.
I got a little different result, FedEx platform use v1 for delivery options, and we are using v2, it seems there are locations in v1 that are not present in v2 (will send an email to Bob about it). specifically they are  STORE_IN_STORE location type, even I can't get location details but the FedEx platform yes, maybe the client credentials need granted for that.

Now application is excluding locations that don't get detail locations from endpoint v1/locations  (will fix it).

**Comment by jlnmay** [comment]
Fixed it in fedex-app, library is getting correct locations, although we have some differences, version 2 does not get Waukegan IL Walmart
![Screen Shot 2021-12-31 at 16 16 38](https://user-images.githubusercontent.com/6946122/147840169-4ef878e6-8b90-42a7-8c28-f6342e4649ec.png)

**Comment by edgrosvenor** [comment]
That looks better. Can you filter for just office print locations? I suspect that's the cause of the 503 error that Sarah and I encountered. A print order can only be placed at an office print location.

**Comment by jlnmay** [comment]
Yep, will control errors.
There is something to consider, as you can see the above list, endpoint brings different type of locations, if we want to filter it we need to do it after getting the response, in that case we will have 6 locations from 10. 
Does it work for you?

I did not find in documentation if we pass in a variable to get only OFFICE_PRINT locations. 
FedEx platform show all type of location even your searched in GOOGLE
